In [1]:
#Importing Modules

In [74]:
import os
import pandas as pd
from sqlalchemy import create_engine,text
from dotenv import load_dotenv

In [5]:
pd.set_option('display.max_columns', None)

In [7]:
load_dotenv()

True

In [11]:
username=os.getenv("SNOWFLAKE_USER_NAME")
password=os.getenv("SNOWFLAKE_PASSWORD")
account=os.getenv("SNOWFLAKE_ACCOUNT")
warehouse=os.getenv("SNOWFLAKE_WAREHOUSE")

In [15]:
try:
    engine = create_engine(f'snowflake://{username}:{password}@{account}?warehouse={warehouse}')
    conn=engine.connect()
    print('Connection established successfully')
except Exception as Error:
    print('An Error occured : {}'.format(Error))

Connection established successfully

In [17]:
customer_master_df = pd.read_csv('Datasets/customer_master.csv')

In [21]:
customer_master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_id                25000 non-null  object
 1   customer_name              25000 non-null  object
 2   customer_age               25000 non-null  int64
 3   gender                     25000 non-null  object
 4   customer_segment           25000 non-null  object
 5   customer_city              25000 non-null  object
 6   customer_state             25000 non-null  object
 7   customer_country           25000 non-null  object
 8   region                     25000 non-null  object
 9   customer_postal_code       25000 non-null  int64
 10  customer_acquisition_cost  25000 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

In [23]:
customer_master_df.head()

,customer_id,customer_name,customer_age,gender,customer_segment,customer_city,customer_state,customer_country,region,customer_postal_code,customer_acquisition_cost
0,CUST-000001,Donna Miller,54,Female,Consumer,Laurenland,Dubai,UAE,South,11253,13.58
1,CUST-000002,Joseph James,61,Male,Consumer,Lake Peter,Lower Saxony,Germany,North,47778,27.45
2,CUST-000003,Daniel Smith,47,Male,Consumer,Seanview,North Rhine,Germany,West,13900,31.53
3,CUST-000004,David Lopez,30,Male,VIP,Hawkinshaven,Pennsylvania,USA,East,53984,16.02
4,CUST-000005,Dakota Davis,55,Female,Consumer,New Carlymouth,Florida,USA,South,50994,41.34

In [29]:
try:
    records_loaded=customer_master_df.to_sql('CUSTOMER_MASTER',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')
    print('Data Loaded Successfully')
    print('Number of Records Loaded : {}'.format(records_loaded))
except Exception as Error:
    print('An Error occured : {}'.format(Error))

C:\Users\ranar\AppData\Local\Temp\ipykernel_13528\2931771406.py:2: UserWarning: The provided table name 'CUSTOMER_MASTER' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  records_loaded=customer_master_df.to_sql('CUSTOMER_MASTER',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')

Data Loaded Successfully
Number of Records Loaded : 25000

In [31]:
data_statistics_df = pd.read_csv('Datasets/dataset_statistics.csv')

In [35]:
data_statistics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Total Transactions   1 non-null      int64
 1   Total Columns        1 non-null      int64
 2   Total Customers      1 non-null      int64
 3   Total Products Used  1 non-null      int64
 4   Date Range           1 non-null      object
 5   Total Revenue        1 non-null      object
 6   Total Profit         1 non-null      object
 7   Average Order Value  1 non-null      object
 8   Average Rating       1 non-null      float64
 9   Return Rate          1 non-null      object
 10  Cancellation Rate    1 non-null      object
dtypes: float64(1), int64(4), object(6)
memory usage: 220.0+ bytes

In [37]:
data_statistics_df.head()

,Total Transactions,Total Columns,Total Customers,Total Products Used,Date Range,Total Revenue,Total Profit,Average Order Value,Average Rating,Return Rate,Cancellation Rate
0,138116,46,24911,138116,2021-01-01 to 2025-12-31,"$177,134,263.74","$76,146,395.76","$1,282.50",3.68,6.85%,6.08%

In [39]:
try:
    records_loaded=data_statistics_df.to_sql('DATASET_STATISTICS',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')
    print('Data Loaded Successfully')
    print('Number of Records Loaded : {}'.format(records_loaded))
except Exception as Error:
    print('An Error occured : {}'.format(Error))

C:\Users\ranar\AppData\Local\Temp\ipykernel_13528\1069117973.py:2: UserWarning: The provided table name 'DATASET_STATISTICS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  records_loaded=data_statistics_df.to_sql('DATASET_STATISTICS',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')

Data Loaded Successfully
Number of Records Loaded : 1

In [41]:
ecommerce_sales_customer_analytics_df = pd.read_csv('Datasets/ecommerce_sales_customer_analytics_150k.csv')

In [43]:
ecommerce_sales_customer_analytics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), object(27)
memory usage: 47.6+ MB

In [45]:
ecommerce_sales_customer_analytics_df.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,customer_city,customer_state,customer_country,region,customer_postal_code,payment_method,payment_status,currency,shipping_method,warehouse,delivery_days,estimated_delivery_days,delivery_status,return_status,return_reason,customer_rating,review_sentiment,customer_review,marketing_channel,campaign_name,coupon_code,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,Loyal,Lake Williamberg,Texas,USA,South,86040,Digital Wallet,Paid,USD,Standard,WH-003,3.0,3.0,On Time,NaN,NaN,3.5,Positive,Satisfied with the purchase.,Direct,Default_Campaign,NaN,94,44,5,1350.19,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,Loyal,Kristyport,Baden-Württemberg,Germany,South,62538,Debit Card,Pending,EUR,Economy,WH-005,10.0,10.0,On Time,NaN,NaN,3.6,Positive,Good value for money.,Direct,Default_Campaign,NaN,201,171,8,3144.64,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,Loyal,Singletonhaven,New York,USA,East,19993,Cash on Delivery,Paid,USD,Express,WH-015,3.0,3.0,On Time,NaN,NaN,4.3,Positive,Good product. Works as expected.,YouTube,NaN,NaN,46,16,5,522.81,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,Loyal,Wigginsstad,North Carolina,USA,South,66329,Debit Card,Paid,USD,Express,WH-010,2.0,2.0,On Time,NaN,NaN,3.5,Positive,Satisfied with the purchase.,Email Marketing,NaN,NaN,54,10,2,544.62,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,Loyal,New Michaelton,Gujarat,India,West,77306,Digital Wallet,Paid,INR,Standard,WH-013,6.0,5.0,Delayed,NaN,NaN,3.0,Neutral,Mixed feelings about this purchase.,Direct,NaN,NaN,278,147,6,2474.52,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [47]:
try:
    records_loaded=ecommerce_sales_customer_analytics_df.to_sql('ECOMMERCE_SALES_CUSTOMER_ANALYTICS',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')
    print('Data Loaded Successfully')
    print('Number of Records Loaded : {}'.format(records_loaded))
except Exception as Error:
    print('An Error occured : {}'.format(Error))

C:\Users\ranar\AppData\Local\Temp\ipykernel_13528\3235446099.py:2: UserWarning: The provided table name 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  records_loaded=ecommerce_sales_customer_analytics_df.to_sql('ECOMMERCE_SALES_CUSTOMER_ANALYTICS',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART')

Data Loaded Successfully
Number of Records Loaded : 138116

In [49]:
order_items_df = pd.read_csv('Datasets/order_items.csv')

In [51]:
order_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  object
 1   product_id           397569 non-null  object
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), object(2)
memory usage: 36.4+ MB

In [53]:
order_items_df.head()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

In [ ]:
try:
    records_loaded=order_items_df.to_sql('ORDER_ITEMS',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART',chunksize=50000)
    print('Data Loaded Successfully')
    print('Number of Records Loaded : {}'.format(records_loaded))
except Exception as Error:
    print('An Error occured : {}'.format(Error))

In [60]:
product_catalog_df=pd.read_csv('Datasets/product_catalog.csv')

In [62]:
product_catalog_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   object
 1   product_name         1175 non-null   object
 2   product_category     1175 non-null   object
 3   product_subcategory  1175 non-null   object
 4   brand                1175 non-null   object
 5   supplier             1175 non-null   object
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), object(6)
memory usage: 82.7+ KB

In [64]:
product_catalog_df.head()

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [66]:
try:
    records_loaded=product_catalog_df.to_sql('PRODUCT_CATALOG',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART',chunksize=50000)
    print('Data Loaded Successfully')
    print('Number of Records Loaded : {}'.format(records_loaded))
except Exception as Error:
    print('An Error occured : {}'.format(Error))

C:\Users\ranar\AppData\Local\Temp\ipykernel_13528\4262927417.py:2: UserWarning: The provided table name 'PRODUCT_CATALOG' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  records_loaded=product_catalog_df.to_sql('PRODUCT_CATALOG',con=conn,index=False,if_exists='append',schema='DATA_ANALYTICS.ECOMMERCEMART',chunksize=50000)

Data Loaded Successfully
Number of Records Loaded : 1175

In [80]:
r=conn.execute(text("""select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE from DATA_ANALYTICS.INFORMATION_SCHEMA.COLUMNS where TABLE_SCHEMA = 'ECOMMERCEMART'
"""))

In [82]:
r.fetchall()

[('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'IS_REPEAT_CUSTOMER', 'BOOLEAN'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_POSTAL_CODE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Revenue', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'RETURN_REASON', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_REVIEW', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'DELIVERY_STATUS', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_CITY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'REGION', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'REGION', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_CITY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Return Rate', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'LOYALTY_POINTS_REDEEMED', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Average Rating', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'PAYMENT_STATUS', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'GENDER', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'DISCOUNT_PERCENTAGE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'RETURN_STATUS', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Customers', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_SEGMENT', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'PRODUCT_COST', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'DISCOUNT_AMOUNT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_NAME', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'GROSS_SALES', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'SHIPPING_COST', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'TAX_AMOUNT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CURRENCY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_NAME', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Products Used', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'LOYALTY_POINTS_EARNED', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'ORDER_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Average Order Value', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'DELIVERY_DAYS', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_NAME', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'UNIT_PRICE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_ORDER_COUNT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'MARKETING_CHANNEL', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'NET_SALES', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'SHIPPING_METHOD', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_ACQUISITION_COST', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Date Range', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'PROFIT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'ORDER_STATUS', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'PRODUCT_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_CATEGORY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_COUNTRY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_TYPE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'WAREHOUSE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_STATE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'BRAND', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Cancellation Rate', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'UNIT_PRICE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'QUANTITY', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_RATING', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'GROSS_SALES', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'DISCOUNT_AMOUNT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_SEGMENT', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_COUNTRY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'SUPPLIER', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'NET_SALES', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'ORDER_DATE', 'DATE'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'TAX_AMOUNT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'ESTIMATED_DELIVERY_DAYS', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Columns', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'SALES_CHANNEL', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_COST', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_AGE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'ORDER_TIME', 'TIME'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'PRODUCT_COST', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Transactions', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_RATING', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'PROFIT', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'DATASET_STATISTICS', 'Total Profit', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'PAYMENT_METHOD', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_POSTAL_CODE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'CUSTOMER_MASTER', 'CUSTOMER_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'QUANTITY', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CAMPAIGN_NAME', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_STATE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_AGE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'PROFIT_MARGIN_PERCENTAGE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ORDER_ITEMS', 'ORDER_ID', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'CUSTOMER_LIFETIME_VALUE', 'NUMBER'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'REVIEW_SENTIMENT', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'PRODUCT_CATALOG', 'PRODUCT_SUBCATEGORY', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'GENDER', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'COUPON_CODE', 'TEXT'),
 ('DATA_ANALYTICS', 'ECOMMERCEMART', 'ECOMMERCE_SALES_CUSTOMER_ANALYTICS', 'SHIPPING_COST', 'NUMBER')]

In [90]:
r.keys()

RMKeyView(['table_catalog', 'table_schema', 'table_name', 'column_name', 'data_type'])

In [94]:
columns = [desc for desc in r.keys()] if r.keys() else []
columns

['table_catalog', 'table_schema', 'table_name', 'column_name', 'data_type']

In [98]:
list(r.keys())

['table_catalog', 'table_schema', 'table_name', 'column_name', 'data_type']